# -*- coding: utf-8 -*-
"""kinh tế lượng ứng dụng

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fQGxHwyWcsmx-XZNmE0qO5kB6sFzOuJ
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df2011 = pd.read_stata("SME data 2011.dta")

df2011.head()

from google.colab import files

uploaded = files.upload()

import pandas as pd

df2013 = pd.read_stata("SME data 2013.dta")

df2013.head()

reader = pd.read_stata(
    "SME data 2013.dta",
    iterator=True
)

labels = reader.variable_labels()

label_df_2013 = pd.DataFrame({
    "Variable": list(labels.keys()),
    "Description": list(labels.values())
})

label_df_2013.head()

label_df_2013.to_excel(
    "Variable_Labels_2013.xlsx",
    index=False
)

files.download(
    "Variable_Labels_2013.xlsx"
)

df2015 = pd.read_stata(
    "SME data 2015.dta"
)

reader = pd.read_stata(
    "SME data 2015.dta",
    iterator=True
)

labels = reader.variable_labels()

label_df_2015 = pd.DataFrame({
    "Variable": list(labels.keys()),
    "Description": list(labels.values())
})

label_df_2015.to_excel(
    "Variable_Labels_2015.xlsx",
    index=False
)

files.download(
    "Variable_Labels_2015.xlsx"
)

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

import os

os.listdir('/content/drive/MyDrive/SME_Project')

import pandas as pd

df2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2011.xlsx'
)

df2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2013.xlsx'
)

df2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_project/SME_data_2015.xlsx'
)

import os

print(os.path.exists('/content/drive'))
print(os.path.exists('/content/drive/MyDrive'))

import os

print(os.listdir('/content/drive/MyDrive'))

import os

for item in os.listdir('/content/drive/MyDrive'):
    print(repr(item))

import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for f in files:
        if 'SME_data_2011' in f:
            print(os.path.join(root, f))

import pandas as pd

df2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2011.xlsx'
)

df2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2013.xlsx'
)

df2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/SME_data_2015.xlsx'
)

print("Đọc dữ liệu thành công")

labels2011 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2011.xlsx'
)

labels2013 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2013.xlsx'
)

labels2015 = pd.read_excel(
    '/content/drive/MyDrive/SME_Project/Variable_Labels_2015.xlsx'
)

labels2011[
    labels2011['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

labels2013[
    labels2013['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

labels2015[
    labels2015['Description']
    .str.contains(
        'net profit',
        case=False,
        na=False
    )
]

labels2011[
    labels2011['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

labels2013[
    labels2013['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

labels2015[
    labels2015['Description']
    .str.contains(
        'credit|loan|debt',
        case=False,
        na=False
    )
]

labels2011[
    labels2011['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

labels2013[
    labels2013['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

labels2015[
    labels2015['Description']
    .str.contains(
        'total assets',
        case=False,
        na=False
    )
]

labels2011[
    labels2011['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

labels2013[
    labels2013['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

labels2015[
    labels2015['Description']
    .str.contains(
        'labour|labor|employee',
        case=False,
        na=False
    )
]

data2011 = df2011[
    [
        'id',
        'year',
        'qEAinetr10',
        'q73bb_11',
        'qEAqur10',
        'q101a1_11'
    ]
].copy()

data2011.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

data2013 = df2013[
    [
        'id',
        'year',
        'EAq1inetr12',
        'q73bb_13',
        'EAq1qur12',
        'q101a1_13'
    ]
].copy()

data2013.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

data2015 = df2015[
    [
        'id',
        'year',
        'EAq1enetr14',
        'q65bb_15',
        'EAq1hr14',
        'q90at_15'
    ]
].copy()

data2015.columns = [
    'id',
    'year',
    'profit',
    'credit',
    'assets',
    'labor'
]

import pandas as pd

panel = pd.concat(
    [
        data2011,
        data2013,
        data2015
    ],
    ignore_index=True
)

panel.head()

panel.shape

panel['year'].value_counts().sort_index()

panel.isnull().sum()

len(panel)

375/7702

panel_clean = panel.dropna()

panel_clean = panel.dropna()

panel_clean.isnull().sum()

panel_clean.shape

panel_clean.describe()

panel_clean['year'].value_counts().sort_index()

panel_clean

panel_clean.to_excel(
    '/content/drive/MyDrive/SME_Project/panel_clean.xlsx',
    index=False
)

import os

os.path.exists(
    '/content/drive/MyDrive/SME_Project/panel_clean.xlsx'
)

panel.to_excel(
    '/content/drive/MyDrive/SME_Project/panel_raw.xlsx',
    index=False
)

import os

os.path.exists(
    '/content/drive/MyDrive/SME_Project/panel_raw.xlsx'
)

desc = panel_clean[['profit','credit','assets','labor']].describe()

desc.to_excel(
    '/content/drive/MyDrive/SME_Project/descriptive_statistics.xlsx'
)

corr = panel_clean[
    ['profit','credit','assets','labor']
].corr()

corr

corr.to_excel(
    '/content/drive/MyDrive/SME_Project/correlation_matrix.xlsx'
)

panel_clean.groupby('id')['year'].count().value_counts()

!pip install linearmodels

from linearmodels.panel import PanelOLS
import statsmodels.api as sm

panel_fe = panel_clean.set_index(
    ['id','year']
)

X = panel_fe[
    [
        'credit',
        'assets',
        'labor'
    ]
]

X = sm.add_constant(X)

y = panel_fe['profit']

model = PanelOLS(
    y,
    X,
    entity_effects=True
)

result = model.fit(
    cov_type='robust'
)

print(result)

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame()

vif["Variable"] = X.columns

vif["VIF"] = [
    variance_inflation_factor(
        X.values,
        i
    )
    for i in range(X.shape[1])
]

print(vif)

with open(
    '/content/drive/MyDrive/SME_Project/fixed_effects_result.txt',
    'w'
) as f:
    f.write(str(result.summary))

panel_clean['id'].nunique()

panel_clean.groupby('id')['year'].count().value_counts().sort_index()

(panel_clean.groupby('id')['year'].count() == 3).sum()

panel_clean.groupby('id')['year'].count().describe()

import pandas as pd

# 1. Thống kê mô tả
desc = panel_clean[['profit','credit','assets','labor']].describe()

# 2. Ma trận tương quan
corr = panel_clean[['profit','credit','assets','labor']].corr()

# 3. Cấu trúc panel
panel_structure = (
    panel_clean.groupby('id')['year']
    .count()
    .value_counts()
    .sort_index()
    .reset_index()
)

panel_structure.columns = [
    'Number_of_Years_Appearing',
    'Number_of_Firms'
]

# 4. Thông tin tổng quát mẫu
sample_info = pd.DataFrame({
    'Indicator': [
        'Total Observations',
        'Unique Firms',
        'Year 2011 Observations',
        'Year 2013 Observations',
        'Year 2015 Observations'
    ],
    'Value': [
        len(panel_clean),
        panel_clean['id'].nunique(),
        (panel_clean['year']==2011).sum(),
        (panel_clean['year']==2013).sum(),
        (panel_clean['year']==2015).sum()
    ]
})

# 5. Kết quả hồi quy FE
fe_result = pd.DataFrame({
    'Regression_Output': str(result.summary).split('\n')
})

# 6. Xuất Excel
with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Research_Results.xlsx'
) as writer:

    sample_info.to_excel(
        writer,
        sheet_name='Sample_Info',
        index=False
    )

    panel_structure.to_excel(
        writer,
        sheet_name='Panel_Structure',
        index=False
    )

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

    fe_result.to_excel(
        writer,
        sheet_name='Fixed_Effects_Result',
        index=False
    )

print("Xuất file thành công!")

from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Research_Results.xlsx'
)

import numpy as np

panel_clean['ln_profit'] = np.log1p(panel_clean['profit'])

panel_clean['ln_credit'] = np.log1p(panel_clean['credit'])

panel_clean['ln_assets'] = np.log1p(panel_clean['assets'])

panel_clean['ln_labor'] = np.log1p(panel_clean['labor'])

panel_log = panel_clean.set_index(
    ['id','year']
)

from linearmodels.panel import PanelOLS
import statsmodels.api as sm

X = panel_log[
    [
        'ln_credit',
        'ln_assets',
        'ln_labor'
    ]
]

X = sm.add_constant(X)

y = panel_log['ln_profit']

model = PanelOLS(
    y,
    X,
    entity_effects=True
)

result_log = model.fit(
    cov_type='robust'
)

print(result_log.summary)

coef_table = pd.DataFrame({
    'Variable': result_log.params.index,
    'Coefficient': result_log.params.values,
    'P_value': result_log.pvalues.values
})

coef_table

coef_table.to_excel(
    '/content/drive/MyDrive/SME_Project/Regression_Log_Result.xlsx',
    index=False
)

from statsmodels.stats.outliers_influence import variance_inflation_factor

X_vif = panel_clean[
    ['ln_credit',
     'ln_assets',
     'ln_labor']
]

vif = pd.DataFrame()

vif["Variable"] = X_vif.columns

vif["VIF"] = [
    variance_inflation_factor(
        X_vif.values,
        i
    )
    for i in range(X_vif.shape[1])
]

print(vif)

import pandas as pd

coef_table = pd.DataFrame({
    'Coefficient': result_log.params,
    'Std_Error': result_log.std_errors,
    'T_Statistic': result_log.tstats,
    'P_Value': result_log.pvalues,
    'CI_Lower': result_log.conf_int().iloc[:,0],
    'CI_Upper': result_log.conf_int().iloc[:,1]
})

coef_table

model_info = pd.DataFrame({
    'Statistic': [
        'Number of Observations',
        'Number of Firms',
        'R-squared Within',
        'R-squared Between',
        'R-squared Overall',
        'F-statistic Robust',
        'Prob(F-statistic)',
        'Poolability Test',
        'Poolability P-value'
    ],
    'Value': [
        result_log.nobs,
        panel_clean['id'].nunique(),
        result_log.rsquared_within,
        result_log.rsquared_between,
        result_log.rsquared_overall,
        result_log.f_statistic.stat,
        result_log.f_statistic.pval,
        result_log.f_pooled.stat,
        result_log.f_pooled.pval
    ]
})

with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Log_FE_Results.xlsx'
) as writer:

    coef_table.to_excel(
        writer,
        sheet_name='Regression_Coefficients'
    )

    model_info.to_excel(
        writer,
        sheet_name='Model_Information',
        index=False
    )

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

print("Đã xuất thành công!")

from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Log_FE_Results.xlsx'
)

import pandas as pd

# ====== BẢNG HỆ SỐ HỒI QUY ======
coef_table = pd.DataFrame({
    'Coefficient': result_log.params,
    'Std_Error': result_log.std_errors,
    'T_Statistic': result_log.tstats,
    'P_Value': result_log.pvalues,
    'CI_Lower': result_log.conf_int().iloc[:,0],
    'CI_Upper': result_log.conf_int().iloc[:,1]
})

# ====== THÔNG TIN MÔ HÌNH ======
model_info = pd.DataFrame({
    'Statistic': [
        'Number of Observations',
        'Number of Firms',
        'R-squared Within',
        'R-squared Between',
        'R-squared Overall',
        'F-statistic Robust',
        'Prob(F-statistic)',
        'Poolability Test',
        'Poolability P-value'
    ],
    'Value': [
        result_log.nobs,
        panel_clean['id'].nunique(),
        result_log.rsquared_within,
        result_log.rsquared_between,
        result_log.rsquared_overall,
        result_log.f_statistic.stat,
        result_log.f_statistic.pval,
        result_log.f_pooled.stat,
        result_log.f_pooled.pval
    ]
})

# ====== XUẤT FILE ======
with pd.ExcelWriter(
    '/content/drive/MyDrive/SME_Project/Final_Research_Output.xlsx'
) as writer:

    desc.to_excel(
        writer,
        sheet_name='Descriptive_Statistics'
    )

    corr.to_excel(
        writer,
        sheet_name='Correlation_Matrix'
    )

    vif.to_excel(
        writer,
        sheet_name='VIF_Test',
        index=False
    )

    coef_table.to_excel(
        writer,
        sheet_name='FE_Log_Result'
    )

    model_info.to_excel(
        writer,
        sheet_name='Model_Information',
        index=False
    )

print("Đã tạo file Final_Research_Output.xlsx")

from google.colab import files

files.download(
    '/content/drive/MyDrive/SME_Project/Final_Research_Output.xlsx'
)